[versions]
agp = "8.4.2"
compose-test = "1.7.8"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.0" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-test" }
compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-test" }
core = { module = "androidx.core:core-ktx", version = "1.13.1" }
preference = { module = "androidx.preference:preference-ktx", version = "1.2.1" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
