[versions]
agp = "8.4.2"
compose-test = "1.6.8"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.0" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-test" }
compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-test" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
